In [57]:
import pandas as pd

pd.set_option('display.max_columns', None)
df = pd.read_csv("../dataset/Loan_Default.csv")
df.head()

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,construction_type,occupancy_type,Secured_by,total_units,income,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
0,24890,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,116500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,118000.0,sb,pr,home,1U,1740.0,EXP,758,CIB,25-34,to_inst,98.728814,south,direct,1,45.0
1,24891,2019,cf,Male,nopre,type2,p1,l1,nopc,b/c,206500,NaN,NaN,NaN,360.0,not_neg,not_int,lpsm,NaN,sb,pr,home,1U,4980.0,EQUI,552,EXP,55-64,to_inst,NaN,North,direct,1,NaN
2,24892,2019,cf,Male,pre,type1,p1,l1,nopc,nob/c,406500,4.56,0.2000,595.0,360.0,neg_amm,not_int,not_lpsm,508000.0,sb,pr,home,1U,9480.0,EXP,834,CIB,35-44,to_inst,80.019685,south,direct,0,46.0
3,24893,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,456500,4.25,0.6810,NaN,360.0,not_neg,not_int,not_lpsm,658000.0,sb,pr,home,1U,11880.0,EXP,587,CIB,45-54,not_inst,69.376900,North,direct,0,42.0
4,24894,2019,cf,Joint,pre,type1,p1,l1,nopc,nob/c,696500,4.00,0.3042,0.0,360.0,not_neg,not_int,not_lpsm,758000.0,sb,pr,home,1U,10440.0,CRIF,602,EXP,25-34,not_inst,91.886544,North,direct,0,39.0

In [58]:
df=df.drop(columns=['Credit_Worthiness'])

In [59]:
df=df[df['term'] >= 360]
df.shape

(121685, 33)

In [60]:
df=df.drop(columns=['LTV'])

In [61]:
df['LTV'] = ( df['loan_amount']/df['property_value'])

In [62]:
df=df.drop(columns=['Interest_rate_spread'])

In [63]:
benchmark_rate = 6.5 
df['Interest_rate_spread'] = df['rate_of_interest'] - benchmark_rate

In [64]:
df=df.drop(columns=['loan_type','loan_purpose','rate_of_interest','construction_type','Upfront_charges'])

In [65]:
df

,ID,year,loan_limit,Gender,approv_in_adv,open_credit,business_or_commercial,loan_amount,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,occupancy_type,Secured_by,total_units,income,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,Region,Security_Type,Status,dtir1,LTV,Interest_rate_spread
0,24890,2019,cf,Sex Not Available,nopre,nopc,nob/c,116500,360.0,not_neg,not_int,not_lpsm,118000.0,pr,home,1U,1740.0,EXP,758,CIB,25-34,to_inst,south,direct,1,45.0,0.987288,NaN
1,24891,2019,cf,Male,nopre,nopc,b/c,206500,360.0,not_neg,not_int,lpsm,NaN,pr,home,1U,4980.0,EQUI,552,EXP,55-64,to_inst,North,direct,1,NaN,NaN,NaN
2,24892,2019,cf,Male,pre,nopc,nob/c,406500,360.0,neg_amm,not_int,not_lpsm,508000.0,pr,home,1U,9480.0,EXP,834,CIB,35-44,to_inst,south,direct,0,46.0,0.800197,-1.940
3,24893,2019,cf,Male,nopre,nopc,nob/c,456500,360.0,not_neg,not_int,not_lpsm,658000.0,pr,home,1U,11880.0,EXP,587,CIB,45-54,not_inst,North,direct,0,42.0,0.693769,-2.250
4,24894,2019,cf,Joint,pre,nopc,nob/c,696500,360.0,not_neg,not_int,not_lpsm,758000.0,pr,home,1U,10440.0,CRIF,602,EXP,25-34,not_inst,North,direct,0,39.0,0.918865,-2.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148661,173551,2019,cf,Sex Not Available,nopre,nopc,b/c,346500,360.0,not_neg,not_int,not_lpsm,358000.0,pr,home,1U,NaN,EXP,585,CIB,25-34,to_inst,south,direct,1,NaN,0.967877,NaN
148662,173552,2019,cf,Joint,nopre,nopc,nob/c,646500,360.0,not_neg,int_only,not_lpsm,828000.0,pr,home,1U,13500.0,CIB,873,EXP,45-54,not_inst,North,direct,0,31.0,0.780797,-2.875
148663,173553,2019,cf,Male,nopre,nopc,b/c,106500,360.0,not_neg,not_int,not_lpsm,NaN,pr,home,1U,1860.0,EQUI,619,EXP,<25,to_inst,North,direct,1,NaN,NaN,NaN
148664,173554,2019,cf,Joint,nopre,nopc,b/c,156500,360.0,not_neg,not_int,not_lpsm,158000.0,pr,home,1U,4020.0,EXP,859,EXP,65-74,to_inst,central,direct,0,45.0,0.990506,-2.510
148666,173556,2019,cf,Male,nopre,nopc,nob/c,586500,360.0,not_neg,not_int,not_lpsm,788000.0,ir,home,4U,7140.0,CIB,569,CIB,25-34,not_inst,south,direct,0,15.0,0.744289,-1.310

In [66]:
df['occupancy_type'].value_counts()

occupancy_type
pr    113060
ir      6151
sr      2474
Name: count, dtype: int64

In [67]:
df

,ID,year,loan_limit,Gender,approv_in_adv,open_credit,business_or_commercial,loan_amount,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,occupancy_type,Secured_by,total_units,income,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,Region,Security_Type,Status,dtir1,LTV,Interest_rate_spread
0,24890,2019,cf,Sex Not Available,nopre,nopc,nob/c,116500,360.0,not_neg,not_int,not_lpsm,118000.0,pr,home,1U,1740.0,EXP,758,CIB,25-34,to_inst,south,direct,1,45.0,0.987288,NaN
1,24891,2019,cf,Male,nopre,nopc,b/c,206500,360.0,not_neg,not_int,lpsm,NaN,pr,home,1U,4980.0,EQUI,552,EXP,55-64,to_inst,North,direct,1,NaN,NaN,NaN
2,24892,2019,cf,Male,pre,nopc,nob/c,406500,360.0,neg_amm,not_int,not_lpsm,508000.0,pr,home,1U,9480.0,EXP,834,CIB,35-44,to_inst,south,direct,0,46.0,0.800197,-1.940
3,24893,2019,cf,Male,nopre,nopc,nob/c,456500,360.0,not_neg,not_int,not_lpsm,658000.0,pr,home,1U,11880.0,EXP,587,CIB,45-54,not_inst,North,direct,0,42.0,0.693769,-2.250
4,24894,2019,cf,Joint,pre,nopc,nob/c,696500,360.0,not_neg,not_int,not_lpsm,758000.0,pr,home,1U,10440.0,CRIF,602,EXP,25-34,not_inst,North,direct,0,39.0,0.918865,-2.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148661,173551,2019,cf,Sex Not Available,nopre,nopc,b/c,346500,360.0,not_neg,not_int,not_lpsm,358000.0,pr,home,1U,NaN,EXP,585,CIB,25-34,to_inst,south,direct,1,NaN,0.967877,NaN
148662,173552,2019,cf,Joint,nopre,nopc,nob/c,646500,360.0,not_neg,int_only,not_lpsm,828000.0,pr,home,1U,13500.0,CIB,873,EXP,45-54,not_inst,North,direct,0,31.0,0.780797,-2.875
148663,173553,2019,cf,Male,nopre,nopc,b/c,106500,360.0,not_neg,not_int,not_lpsm,NaN,pr,home,1U,1860.0,EQUI,619,EXP,<25,to_inst,North,direct,1,NaN,NaN,NaN
148664,173554,2019,cf,Joint,nopre,nopc,b/c,156500,360.0,not_neg,not_int,not_lpsm,158000.0,pr,home,1U,4020.0,EXP,859,EXP,65-74,to_inst,central,direct,0,45.0,0.990506,-2.510
148666,173556,2019,cf,Male,nopre,nopc,nob/c,586500,360.0,not_neg,not_int,not_lpsm,788000.0,ir,home,4U,7140.0,CIB,569,CIB,25-34,not_inst,south,direct,0,15.0,0.744289,-1.310

In [68]:
df['Secured_by'].value_counts()

Secured_by
home    121658
land        27
Name: count, dtype: int64

In [69]:
df

,ID,year,loan_limit,Gender,approv_in_adv,open_credit,business_or_commercial,loan_amount,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,occupancy_type,Secured_by,total_units,income,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,Region,Security_Type,Status,dtir1,LTV,Interest_rate_spread
0,24890,2019,cf,Sex Not Available,nopre,nopc,nob/c,116500,360.0,not_neg,not_int,not_lpsm,118000.0,pr,home,1U,1740.0,EXP,758,CIB,25-34,to_inst,south,direct,1,45.0,0.987288,NaN
1,24891,2019,cf,Male,nopre,nopc,b/c,206500,360.0,not_neg,not_int,lpsm,NaN,pr,home,1U,4980.0,EQUI,552,EXP,55-64,to_inst,North,direct,1,NaN,NaN,NaN
2,24892,2019,cf,Male,pre,nopc,nob/c,406500,360.0,neg_amm,not_int,not_lpsm,508000.0,pr,home,1U,9480.0,EXP,834,CIB,35-44,to_inst,south,direct,0,46.0,0.800197,-1.940
3,24893,2019,cf,Male,nopre,nopc,nob/c,456500,360.0,not_neg,not_int,not_lpsm,658000.0,pr,home,1U,11880.0,EXP,587,CIB,45-54,not_inst,North,direct,0,42.0,0.693769,-2.250
4,24894,2019,cf,Joint,pre,nopc,nob/c,696500,360.0,not_neg,not_int,not_lpsm,758000.0,pr,home,1U,10440.0,CRIF,602,EXP,25-34,not_inst,North,direct,0,39.0,0.918865,-2.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148661,173551,2019,cf,Sex Not Available,nopre,nopc,b/c,346500,360.0,not_neg,not_int,not_lpsm,358000.0,pr,home,1U,NaN,EXP,585,CIB,25-34,to_inst,south,direct,1,NaN,0.967877,NaN
148662,173552,2019,cf,Joint,nopre,nopc,nob/c,646500,360.0,not_neg,int_only,not_lpsm,828000.0,pr,home,1U,13500.0,CIB,873,EXP,45-54,not_inst,North,direct,0,31.0,0.780797,-2.875
148663,173553,2019,cf,Male,nopre,nopc,b/c,106500,360.0,not_neg,not_int,not_lpsm,NaN,pr,home,1U,1860.0,EQUI,619,EXP,<25,to_inst,North,direct,1,NaN,NaN,NaN
148664,173554,2019,cf,Joint,nopre,nopc,b/c,156500,360.0,not_neg,not_int,not_lpsm,158000.0,pr,home,1U,4020.0,EXP,859,EXP,65-74,to_inst,central,direct,0,45.0,0.990506,-2.510
148666,173556,2019,cf,Male,nopre,nopc,nob/c,586500,360.0,not_neg,not_int,not_lpsm,788000.0,ir,home,4U,7140.0,CIB,569,CIB,25-34,not_inst,south,direct,0,15.0,0.744289,-1.310

In [70]:
df['total_units'].value_counts()

total_units
1U    119733
2U      1316
3U       341
4U       295
Name: count, dtype: int64

In [71]:
df['credit_type'].value_counts()

credit_type
CIB     39267
CRIF    36116
EXP     34132
EQUI    12170
Name: count, dtype: int64

In [72]:
df=df.drop(columns=['Security_Type','Gender','co-applicant_credit_type','submission_of_application','approv_in_adv'])

In [73]:
df

,ID,year,loan_limit,open_credit,business_or_commercial,loan_amount,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,occupancy_type,Secured_by,total_units,income,credit_type,Credit_Score,age,Region,Status,dtir1,LTV,Interest_rate_spread
0,24890,2019,cf,nopc,nob/c,116500,360.0,not_neg,not_int,not_lpsm,118000.0,pr,home,1U,1740.0,EXP,758,25-34,south,1,45.0,0.987288,NaN
1,24891,2019,cf,nopc,b/c,206500,360.0,not_neg,not_int,lpsm,NaN,pr,home,1U,4980.0,EQUI,552,55-64,North,1,NaN,NaN,NaN
2,24892,2019,cf,nopc,nob/c,406500,360.0,neg_amm,not_int,not_lpsm,508000.0,pr,home,1U,9480.0,EXP,834,35-44,south,0,46.0,0.800197,-1.940
3,24893,2019,cf,nopc,nob/c,456500,360.0,not_neg,not_int,not_lpsm,658000.0,pr,home,1U,11880.0,EXP,587,45-54,North,0,42.0,0.693769,-2.250
4,24894,2019,cf,nopc,nob/c,696500,360.0,not_neg,not_int,not_lpsm,758000.0,pr,home,1U,10440.0,CRIF,602,25-34,North,0,39.0,0.918865,-2.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148661,173551,2019,cf,nopc,b/c,346500,360.0,not_neg,not_int,not_lpsm,358000.0,pr,home,1U,NaN,EXP,585,25-34,south,1,NaN,0.967877,NaN
148662,173552,2019,cf,nopc,nob/c,646500,360.0,not_neg,int_only,not_lpsm,828000.0,pr,home,1U,13500.0,CIB,873,45-54,North,0,31.0,0.780797,-2.875
148663,173553,2019,cf,nopc,b/c,106500,360.0,not_neg,not_int,not_lpsm,NaN,pr,home,1U,1860.0,EQUI,619,<25,North,1,NaN,NaN,NaN
148664,173554,2019,cf,nopc,b/c,156500,360.0,not_neg,not_int,not_lpsm,158000.0,pr,home,1U,4020.0,EXP,859,65-74,central,0,45.0,0.990506,-2.510
148666,173556,2019,cf,nopc,nob/c,586500,360.0,not_neg,not_int,not_lpsm,788000.0,ir,home,4U,7140.0,CIB,569,25-34,south,0,15.0,0.744289,-1.310

In [74]:
df['total_monthly_payment']=(df['dtir1']*df['income'])
df['DTI'] = (df['total_monthly_payment']/df['income'])*100
df['down_payment'] = df['property_value'] - df['loan_amount']

In [75]:
y = df['Status']
X = df[[ 'LTV', 'property_value','total_units','loan_amount','term','Interest_rate_spread','DTI','Credit_Score','down_payment','occupancy_type','Secured_by','Region','income','Neg_ammortization','interest_only','lump_sum_payment']]
X.columns

Index(['LTV', 'property_value', 'total_units', 'loan_amount', 'term',
       'Interest_rate_spread', 'DTI', 'Credit_Score', 'down_payment',
       'occupancy_type', 'Secured_by', 'Region', 'income', 'Neg_ammortization',
       'interest_only', 'lump_sum_payment'],
      dtype='object')

In [76]:
X = X.fillna(X.median(numeric_only=True))
X = pd.get_dummies(X, drop_first=True)
X.isna().sum()

LTV                          0
property_value               0
loan_amount                  0
term                         0
Interest_rate_spread         0
DTI                          0
Credit_Score                 0
down_payment                 0
income                       0
total_units_2U               0
total_units_3U               0
total_units_4U               0
occupancy_type_pr            0
occupancy_type_sr            0
Secured_by_land              0
Region_North-East            0
Region_central               0
Region_south                 0
Neg_ammortization_not_neg    0
interest_only_not_int        0
lump_sum_payment_not_lpsm    0
dtype: int64

In [77]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [78]:
# %pip install imbalanced-learn

from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=0)
X_resampled, Y_resampled = ros.fit_resample(X_train, y_train)

In [79]:
Y_resampled.value_counts()

Status
0    73782
1    73782
Name: count, dtype: int64

In [80]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    max_depth=5,   # limit tree depth
    random_state=42
)


# Train
rf.fit(X_resampled, Y_resampled)

RandomForestClassifier(max_depth=5, random_state=42)

In [81]:
y_pred= rf.predict(X_test)
y_pred

array([0, 0, 0, ..., 1, 1, 0])

In [82]:
rf.score(X_test, y_test)

0.9177795126761721

In [83]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred, target_names=[str(c) for c in rf.classes_]))

              precision    recall  f1-score   support

           0       0.97      0.92      0.94     18446
           1       0.78      0.92      0.84      5891

    accuracy                           0.92     24337
   macro avg       0.88      0.92      0.89     24337
weighted avg       0.93      0.92      0.92     24337

In [84]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

def evaluate(model, X_test, y_test):
    preds = model.predict(X_test)
    return {
        "Accuracy": accuracy_score(y_test, preds),
        "Precision": precision_score(y_test, preds),
        "Recall": recall_score(y_test, preds),
        "F1": f1_score(y_test, preds),
        "ROC-AUC": roc_auc_score(y_test, preds)
    }

print("Random Forest:", evaluate(rf, X_test, y_test))

Random Forest: {'Accuracy': 0.9177795126761721, 'Precision': 0.7780160091480847, 'Recall': 0.9239517908674248, 'F1': 0.8447272445099713, 'ROC-AUC': 0.9198800480955363}

In [85]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(rf, X, y, cv=5, scoring="accuracy")
print("Cross-validation Accuracy:", scores.mean())

Cross-validation Accuracy: 0.8819246414923778

In [86]:
import joblib
joblib.dump(rf, 'mortgage_default_model.pkl')

['mortgage_default_model.pkl']

In [87]:
import joblib
joblib.dump(list(X.columns), 'mortgage_X_columns.pkl')

['mortgage_X_columns.pkl']